datapath = fullfile('Data','Train400');
ori_img = imread(fullfile(datapath,'test_001.png'));
figure,imshow(ori_img)

imds = imageDatastore(datapath);
img_augmenter = imageDataAugmenter( ...
        'RandXReflection',true, ...
        'RandXScale',[0.5 2], ...
        'RandYReflection',true, ...
        'RandYScale',[0.5 2],...
        'RandRotation',[0,360]);

ds = Dataloader.noiseImageDatastore(imds,...
  'DataAugmentation',img_augmenter,...
  'PatchSize',50,...
  'GaussianNoiseLevel',25/255);

imgs = ds.preview();
figure,montage(imgs.input);
