datapath = fullfile('Data','Train400');
ori_img = imread(fullfile(datapath,'test_001.png'));
figure,imshow(ori_img)

imds = imageDatastore(datapath);
img_augmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXScale',[1 2], ...
    'RandYReflection',true, ...
    'RandYScale',[1 2]);
 

ds = noiseImageDatastore(imds,...
  'DataAugmentation',img_augmenter,...
  'PatchSize',180,...
  'GaussianNoiseLevel',0.00001);

imgs = ds.preview();
figure,montage(imgs.input);