function imds = denoise_datastore(net,datapath)
% create a imageDatastore that denoises images when read
  imds = imageDatastore(datapath,...
      'IncludeSubfolder',true,...
      'FileExtension',{'.jpg','.png','.bmp'},...
      'ReadFcn',@(filename)denoiseImage(im2single(imread(filename)),net));
end